// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWZEliAz9hCeF4kRVsj83Kg_mrinFa3Ug',
    appId: '1:1010801428667:web:50df8635b5ab406635819e',
    messagingSenderId: '1010801428667',
    projectId: 'brightnest-app',
    authDomain: 'brightnest-app.firebaseapp.com',
    storageBucket: 'brightnest-app.appspot.com',
    measurementId: 'G-NC9SX7LTNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhLosECZ0Rd-YZ2_amHXR9D6Pn1lMbUwM',
    appId: '1:1010801428667:android:1a3ee46014aa224035819e',
    messagingSenderId: '1010801428667',
    projectId: 'brightnest-app',
    storageBucket: 'brightnest-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPgTBrkJiHSp50RQLm5ZZz7QC5bPaMZts',
    appId: '1:1010801428667:ios:2fe53c94e7dc229335819e',
    messagingSenderId: '1010801428667',
    projectId: 'brightnest-app',
    storageBucket: 'brightnest-app.appspot.com',
    iosBundleId: 'com.example.brightnestApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPgTBrkJiHSp50RQLm5ZZz7QC5bPaMZts',
    appId: '1:1010801428667:ios:2fe53c94e7dc229335819e',
    messagingSenderId: '1010801428667',
    projectId: 'brightnest-app',
    storageBucket: 'brightnest-app.appspot.com',
    iosBundleId: 'com.example.brightnestApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWZEliAz9hCeF4kRVsj83Kg_mrinFa3Ug',
    appId: '1:1010801428667:web:56078656b42f596b35819e',
    messagingSenderId: '1010801428667',
    projectId: 'brightnest-app',
    authDomain: 'brightnest-app.firebaseapp.com',
    storageBucket: 'brightnest-app.appspot.com',
    measurementId: 'G-CJ460DJXCQ',
  );
}
